repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T02-ROBERTA-WILLIAMS-AlGUSTO-CALDAS-AUGUSTO-DUARTE
repo_name: FCTE-Qualidade-de-Software-1
site_name: Grupo Roberta Williams - Turma 2 (2025.1)
site_description: Documentação do projeto da dupla do grupo Roberta Williams de Qualidade de Software (2025.1), Turma 2

nav:
  - Início: index.md
  - "Propósito de Avalição": fase1/propositoDeAvaliacao.md
  - "Especificação da Avaliação":
      - "Abordagem GQM": fase2/gqm.md
      - "Abstraction Sheets": fase2/sheet.md
  - "Planejamento da Avaliação":
      - "Q-Rapids": fase3/qrapids.md
      - "Plano de Avaliação": fase3/plano.md
      - "Cronograma": fase3/cronograma.md
  - "Execução da Avaliação":
      - "Acessibilidade Visual": fase4/M1.md
      - "Navegabilidade Acessível": fase4/M2.md
      - "Cobertura de Textos Alternativos": fase4/M3.md
      - "Redundância Multissensorial de Feedbacks": fase4/M4.md
  - "Tabela de Contribuição": tabelaDeContribuicao.md

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: orange
      accent: deep orange

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: orange
      accent: deep orange

    - scheme: high-contrast
      primary: orange
      accent: yellow
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast

  logo: assets/img/logo.png
  extra_css: [stylesheets/extra.css]

markdown_extensions:
  - attr_list